POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "ali",
    "password": "p3@SS#o$d"
}
###
GET http://localhost:3000/users
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "ali",
    "password": "p3@SS#o$d"
}